apiVersion: v1
kind: Service
metadata:
  name: forkme
  namespace: forkit
  labels:
    app: forkme
spec:
  selector:
    app: forkme
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
---
# Expose externally (remove if using Ingress instead)
apiVersion: v1
kind: Service
metadata:
  name: forkme-external
  namespace: forkit
  labels:
    app: forkme
spec:
  selector:
    app: forkme
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
  type: LoadBalancer
